name: EventClans
main: me.amori.eventclans.EventClansPlugin
version: 1.0.0
api-version: '1.20'
commands:
  setteam:
    description: "Update the team for a specific player"
  #clan:
  #  description: "Open clan selection panel for neutral players"
  #  aliases: ["clans", "clanpanel"]